#!/bin/sh

# Usage:
# cd deeplearn
# scripts/build_and_lint_all

# These directories have dependencies on each other and so must be built in the
# correct order.  Note this also means they should be published to NPM in the
# same order, so that the dependency versions can be appropriately updated
# along the way.

MODULES="
.
models/squeezenet
models/knn_image_classifier
models/mobilenet
models/yolo_mobilenet
demos
starter/typescript
starter/es6
"

ROOTDIR=`pwd`

for m in $MODULES; do
  echo
  echo =======================================================
  echo Building $m
  echo =======================================================
  cd $m
  yarn run localprep
  yarn run localbuild
  yarn run lint
  cd $ROOTDIR
done
