#!/usr/bin/env node
// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================

const fs = require('fs');
const path = require('path');

const IGNORE_DIRS = ['node_modules', 'dist', 'coverage'];

// List all files in a directory in Node.js recursively in a synchronous fashion
function walkSync(dir, filelist) {
  const files = fs.readdirSync(dir);
  filelist = filelist || [];
  files.forEach(file => {
    if (IGNORE_DIRS.indexOf(file) >= 0 || file.startsWith('.')) {
      return;
    }
    const childPath = path.join(dir, file);
    if (fs.statSync(childPath).isDirectory()) {
      filelist = walkSync(childPath, filelist);
    } else if (file == 'package.json') {
      filelist.push(childPath);
    }
  });
  return filelist;
};

const files = walkSync(process.cwd());
console.log(files);
