#!/usr/bin/env node
// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================

const fs = require('fs');
const path = require('path');
const shell = require('shelljs');

const IGNORE_DIRS = ['node_modules', 'dist', 'coverage'];

function run(cmd, filePath) {
  if (shell.exec(cmd).code !== 0) {
    shell.echo('Failed running', cmd, 'on', filePath);
    shell.exit(1);
  }
}

const cwd = process.cwd();
shell.echo('=======================================================');
shell.echo('Building', cwd);
run('yarn', cwd);
run('yarn build', cwd);
run('yarn lint', cwd);
